# Etiquetas para tipos de cambios
bug:
  - '**/*.py'
  - '!**/tests/**'
  - '!**/docs/**'
  - '!**/examples/**'
  - '!**/scripts/**'
  - '!**/tools/**'
  - '!**/utils/**'
  - '!**/__init__.py'
  - '!**/setup.py'
  - '!**/requirements*.txt'
  - '!**/README.md'
  - '!**/LICENSE'
  - '!**/CHANGELOG.md'
  - '!**/CONTRIBUTING.md'
  - '!**/SECURITY.md'
  - '!**/.gitignore'
  - '!**/.editorconfig'
  - '!**/.flake8'
  - '!**/.isort.cfg'
  - '!**/.mypy.ini'
  - '!**/pytest.ini'
  - '!**/.pre-commit-config.yaml'
  - '!**/Dockerfile'
  - '!**/docker-compose.yml'
  - '!**/.dockerignore'
  - '!**/.github/**'

feature:
  - '**/*.py'
  - '!**/tests/**'
  - '!**/docs/**'
  - '!**/examples/**'
  - '!**/scripts/**'
  - '!**/tools/**'
  - '!**/utils/**'
  - '!**/__init__.py'
  - '!**/setup.py'
  - '!**/requirements*.txt'
  - '!**/README.md'
  - '!**/LICENSE'
  - '!**/CHANGELOG.md'
  - '!**/CONTRIBUTING.md'
  - '!**/SECURITY.md'
  - '!**/.gitignore'
  - '!**/.editorconfig'
  - '!**/.flake8'
  - '!**/.isort.cfg'
  - '!**/.mypy.ini'
  - '!**/pytest.ini'
  - '!**/.pre-commit-config.yaml'
  - '!**/Dockerfile'
  - '!**/docker-compose.yml'
  - '!**/.dockerignore'
  - '!**/.github/**'

documentation:
  - '**/docs/**'
  - '**/README.md'
  - '**/LICENSE'
  - '**/CHANGELOG.md'
  - '**/CONTRIBUTING.md'
  - '**/SECURITY.md'

tests:
  - '**/tests/**'
  - '**/pytest.ini'

dependencies:
  - '**/requirements*.txt'
  - '**/setup.py'

# Etiquetas para áreas del proyecto
frontend:
  - '**/app/static/**'
  - '**/app/templates/**'

backend:
  - '**/app/**'
  - '!**/app/static/**'
  - '!**/app/templates/**'

infrastructure:
  - '**/Dockerfile'
  - '**/docker-compose.yml'
  - '**/.dockerignore'
  - '**/.github/**'
  - '**/.gitignore'
  - '**/.editorconfig'
  - '**/.flake8'
  - '**/.isort.cfg'
  - '**/.mypy.ini'
  - '**/pytest.ini'
  - '**/.pre-commit-config.yaml' 