version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - SECRET_KEY=dev
      - DATABASE_URL=sqlite:///smartina.db
    volumes:
      - .:/app
      - smartina_data:/app/instance
    command: gunicorn --bind 0.0.0.0:5000 run:app

volumes:
  smartina_data: 